### ISSUE TITLE
Есть ли поддержка чтения данных с шины без запроса?

### ISSUE THREAD

**Issue by ashumkin** [wirenboard/wb-mqtt-serial#536]
Ситуация такая: у меня есть газовый сигнализатор ([такой](http://sargazcom.ru/catalogue/gas_equipment/93/)). У него есть шина "Линия". Это, судя по [доке (Приложение А)](http://sargazcom.ru/common/sgkszb_ry.pdf) и по моим исследованим, RS-485. На ней периодически идёт "широковещательный" пакет с текущим статусом. Периодичность ~ 1 раз в 5 секунд. При срабатывании - чаще: 1 раз в секунду. Вроде бы, на 9600 8N1. По крайней мере, данные на ней стабильно одинаковые.

Производитель не даёт информации об используемом протоколе, чтобы можно было делать "запрос-ответ" (что  значительно бы упростило бы задачу; реверсить - нет опыта и, тем более, данных, т.к. нет управляющей стороны).

Решение в лоб, конечно, - повесить "Линию" на отдельную шину в WB, написать простенький скрипт на питоне, и писать в топик текущий статус.

Однако, выделять для этого отдельную шину - по-моему, слишком расточительно (и, в общем случае, не всегда могут быть свободные).

Вопрос: есть ли в `wb-mqtt-serial` возможность создать шаблон устройства такого типа (без "запрос-ответ"), принимать эти широковещательные посылки, и привязывать их к заданным устройствам?

Если нет, то оцените примерно возможность доработки, и ткните пальцем в код, где и примерно как это можно было бы сделать (я ещё не погружался в код (да и я не С++ разработчик), но, если доработка не сильно сложная (для чего и нужна оценка), я, возможно, смог бы сделать патч, ну и PR)

**Comment by wb-adegtyarev** [comment]
Задавайте, пожалуйста, вопросы на портале. Его читает техподдержка, разработчики и другие пользователи, которые смогут вам ответить или помочь. А на Гитхабе мы с радостью примем пуллреквеста, если вы сможете предложить улучшения.

Тема на портале: https://support.wirenboard.com/t/est-li-podderzhka-chteniya-dannyh-s-shiny-bez-zaprosa/13368
