### ISSUE TITLE
mqtt controls meta readonly

### ISSUE THREAD

**Issue by andreypopov** [wirenboard/wb-mqtt-serial#74]
Нужно пройтись по всем контролам и правильно расставить мету, почему не стоит readonly у CO2 контрола или у /devices/system/#

mosquitto_sub  -t "/devices/+/meta/+" -v

/devices/wbrules/controls/Rule debugging/meta/type switch
/devices/wbrules/controls/Rule debugging/meta/order 1
/devices/system/controls/Batch No/meta/type text
/devices/system/controls/Batch No/meta/order 1
/devices/system/controls/Current uptime/meta/type text
/devices/system/controls/Current uptime/meta/order 2
/devices/system/controls/DTS Version/meta/type text
/devices/system/controls/DTS Version/meta/order 3
/devices/system/controls/Firmware version/meta/type text
/devices/system/controls/Firmware version/meta/order 4
/devices/sensor1/controls/Air Quality (VOC)/meta/type concentration
**/devices/sensor1/controls/Air Quality (VOC)/meta/readonly 1**
/devices/sensor1/controls/Air Quality (VOC)/meta/order 3
/devices/sensor1/controls/CO2/meta/type concentration
/devices/sensor1/controls/CO2/meta/order 4
/devices/sensor1/controls/Sound Level/meta/type sound_level
**/devices/sensor1/controls/Sound Level/meta/readonly 1**
/devices/sensor1/controls/Sound Level/meta/order 5

**Comment by sikmir** [comment]
Не актуально, meta/readonly уже корректно выставлено.
