### ISSUE TITLE
Консультация по интеграции счетчика Тайпит Нева 320 в умный дом

### ISSUE THREAD

**Issue by 0anton** [wirenboard/wb-mqtt-serial#786]
Прошу прощение за использование Issue не по назначению - мне нужная (платная) консультация с @KraPete по поводу интеграции счетчика Тайпит Нева 320 в "умный дом".

Относится к файлам:
- https://github.com/wirenboard/wb-mqtt-serial/blob/master/src/devices/neva_device.cpp
- https://github.com/wirenboard/wb-mqtt-serial/blob/master/templates/config-neva-mt32x.json

**Comment by KraPete** [comment]
Пишите на [портал ТП](https://support.wirenboard.com), постараемся помочь.
