### ISSUE TITLE
PU3 панель термостата

### ISSUE THREAD

**Issue by Popov2006** [wirenboard/wb-mqtt-serial#97]
конфиг панельки управления температурой и скоростью вентилятора.  Панель имеет только порт RS 485 Modbus и питание.

{
   "device_type":"TemperatureControlPanel",
   "device":{
      "name":"Temperature Control Panel",
      "id":"temp",
      "max_read_registers":0,
      "channels":[
         {
            "name":"Current temperature",
            "reg_type":"holding",
            "readonly":false,
            "address":0,
            "type":"temperature",
            "scale":0.1,
            "format":"s16"
         },
{
            "name":"Mode",
            "reg_type":"holding",
            "readonly":false,
            "address":3,
            "type":"value",
            "scale":1,
            "format":"s16"
         },
{
            "name":"Speed Vent",
            "reg_type":"holding",
            "readonly":false,
            "address":4,
            "type":"range",
            "scale":1,
            "max":5
         },
{
            "name":"Temperature Set",
            "reg_type":"holding",
            "readonly":false,
            "address":1,
            "type":"range",
            "scale":0.1,
	    "max":35
          },
         {
            "name":"The thermostat works",
            "reg_type":"holding",
            "readonly":false,
            "address":2,
            "type":"switch"

          },
{
            "name":"Outdoor temperature",
            "reg_type":"holding",
            "readonly":false,
            "address":9,
            "type":"value",
            "scale":0.1,
            "format":"s16"
           }
        
      ]
   }
}

**Comment by Popov2006** [comment]
Внешний вид устройства в Девайсах WB

![image](https://user-images.githubusercontent.com/52490000/61614803-4759f000-ac6d-11e9-96ee-67460d73d91d.png)

**Comment by Popov2006** [comment]
из доработок можно наверное завести настройку времени и дня недели. Но я этого пока не делал.

Топики

![image](https://user-images.githubusercontent.com/52490000/61614947-8f791280-ac6d-11e9-80c5-bc333c687c23.png)

**Comment by alexey-gamov** [comment]
Думаю стоит закрыть данный вопрос, так как шаблон [давно реализован](https://github.com/wirenboard/wb-mqtt-serial/blob/master/templates/config-cityron-pu-3.json.jinja) :)

**Comment by sikmir** [comment]
Resolved #366
